import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Select from "react-select";
import { useState } from "react";
import "@coreui/coreui/dist/css/coreui.min.css";
import {
  CCard,
  CCardHeader,
  CCardBody,
  CCardTitle,
  CCardText,
  CListGroup,
  CListGroupItem,
  CButton,
  CFormInput,
} from "@coreui/react";
import { POST } from "../Services/APIService";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [userTaste, setTaste] = useState("");
  const [isLoading, setLoading] = useState(false);
  const [suggestions, setSuggestions] = useState([]);

  const handleSubmit = async () => {
    setLoading(true);
    // console.log(data);
    POST("/", { taste: userTaste })
      .then((resp) => {
        setSuggestions(resp.suggestedMovies);
        setLoading(false);
      })
      .catch(console.log);
  };

  const handleEnterKey = ({keyCode}) => {
    if(keyCode===13) handleSubmit();
  } 

  return (
    <>
      <Head>
        <title>flixGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
            <CFormInput
              type="text"
              placeholder="What are you looking for??"
              onChange={({ target: { value } }) => {
                setTaste(value);
              }}
              onKeyUp={handleEnterKey}
              className={styles["basic-multi-select"]}
            />
            <CButton
              color="light"
              shape="rounded-pill"
              disabled={isLoading}
              style={{ margin: "1px 10px", width: "20%" }}
              onClick={handleSubmit}
              size="sm"
            >
              Get Movies
            </CButton>
        </div>
        <div className={styles.center} style={{ position: "relative" }}>
          <CCard style={{ width: "800px" }}>
            <CCardHeader>Suggestion</CCardHeader>
            <CCardBody>
              <CCardTitle>Movies</CCardTitle>
              <CCardText>
                {suggestions && suggestions.length > 0 && (
                  <CListGroup flush>
                    {suggestions.map((item, index) => (
                      <CListGroupItem key={index}>
                        {item.title}, {item.year}, You can watch on{" "}
                        {item.wheretowatch}
                      </CListGroupItem>
                    ))}
                  </CListGroup>
                )}
              </CCardText>
            </CCardBody>
          </CCard>
        </div>
      </main>
    </>
  );
}
